[package]
name = "okta-token"
version = "0.1.0"
authors = ["Kye Lewis <kye.lewis@techin.site>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = "1"
chrono = "0.4"
scraper = "0.12"
pkce = "0.1"
colored = "2"
clipboard = "0.5"
rpassword = "5.0"